spring.application.name=risk-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/release_guard
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=risk-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topics.release-created=release.created
app.kafka.topics.risk-calculated=risk.calculated

app.risk.cache.key-prefix=risk:cache:
app.risk.cache.ttl-seconds=3600

app.admin.key=local-admin-key

springdoc.swagger-ui.enabled=true
