spring.application.name=release-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/release_guard
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#spring.jackson.serialization.write-dates-as-timestamps=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topics.release-created=release.created
app.kafka.topics.release-status-changed=release.status.changed

github.api.base-url=https://api.github.com
github.token=

springdoc.swagger-ui.enabled=true

























